---
parameters:
  # those parameter are dynamically changed anywhere in the definitions, as long as the key is surrounded by #
  depl_user: hoauser

apps_inventory:
  # - name: pagekit
  #   version: latest
  #   docker_base: 'phusion-docker-php-fpm'
  #   docker_flavors:
  #     - 'docker-php-apps'

  - name: grav_phusion
    version: latest
    docker_base: "hoa-phusion-php-fpm"
    docker_flavors:
      - "docker-php-apps"
      - "php-app-manager"

  - name: wordpress
    image_name: "houseofagile/wordpress"
    version: latest
    docker_base: "hoa-phusion-php-fpm"
    docker_flavors:
      - "ubuntu-hoauser"

  # - name: sylius
  #   version: latest
  #   docker_base: 'hoa-phusion-php-fpm'
  #   docker_flavors:
  #     - 'docker-php-apps'

  - name: docker-nginx-php-fpm
    image_name: "houseofagile/docker-nginx-php-fpm"
    version: latest
    docker_base: "hoa-phusion-baseimage"
    docker_flavors: []

  - name: docker-nginx-symfony
    image_name: "houseofagile/docker-nginx-symfony"
    version: latest
    docker_base: "hoa-phusion-symfony"
    docker_flavors:
      - "docker-php-apps"
      - "ubuntu-hoauser"

  - name: mysql
    version: latest
    docker_base: "mysql"
    docker_flavors: []

  - name: chromebot
    image_name: "houseofagile/docker-chromebot"
    version: latest
    docker_base: "hoa-purephp-nginx-fpm"
    docker_flavors:
      - "ubuntu-hoauser"
      - "php-composer"
      - "chrome-headless"
    compose:
      main:
        name: app
        container_name: popolipopo
        environment:
          - app_log:/app/var/log
        ports:
        volumes:
          - ../:/app
          - /tmp/.X11-unix:/tmp/.X11-unix
          - "/dev/shm:/dev/shm"
          - app_log:/app/var/log
          - app_uploads:/app/uploads          
      env:
        dev:
          environment:
            - DISPLAY=$DISPLAY
          ports:
            - 8080:80
            - 9001:9001
          volumes:
            - ../:/app
            - /tmp/.X11-unix:/tmp/.X11-unix
            - "/dev/shm:/dev/shm"
            - app_log:/app/var/log
            - app_uploads:/app/uploads            
        prod:
          environment:
          ports:
            - 8080:80
          volumes:
            - ./instances/env.prod:/app/.env
            - vol_app_log:/app/var/log
            - "/dev/shm:/dev/shm"
            - vol_app_uploads:/app/uploads            
      sidekicks:
        - name: db
          image: mysql:5.7
          volumes:
            - app_db_vol:/var/lib/mysql
          env_file:
            - .env
        - name: redis
          image: redis:latest

services_inventory:

stacks_inventory:
  # - name: grav_pure
  #   app_main_service: grav_phusion
  #   app_other_services: []

  - name: wordpress
    app_main_service: wordpress
    app_other_services: []
  #
  # - name: docker-try-nginx
  #   app_main_service: docker-nginx-php-fpm
  #   app_other_services: []
  #
  - name: grav_mysql
    app_main_service: grav_phusion
    app_other_services:
      - mysql
